---
# Bring stack Down
- hosts: loadbalancer
  tasks:
          - service: name=nginx state=stopped

- hosts: webserver
  tasks:
          - service: name=apache2 state=stopped            

            # Restart Mysql            
- hosts: database
  tasks:
          - service: name=nginx state=restarted

- hosts: webserver
  tasks:
          - service: name=apache2 state=started

- hosts: loadbalancer
  tasks:
          - service: name=nginx state=started


